spring.application.name=job-assistant

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# ☁️ USE INTERNAL RAILWAY NETWORKING
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# This is a safety fallback for local testing
# spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/railway}

# 🧠 AI CONFIGURATION
groq.api.key=${GROQ_API_KEY:offline}

# ✉️ EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:organization0105@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:rgra hadj zvfl jcta}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 🌐 SERVER CONFIGURATION
server.address=0.0.0.0
server.port=${PORT:8080}