spring.application.name=job-assistant

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# HARDCODED Database Credentials (Safe because repo is private)
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:44941/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=YITXSDdmseOoXHVzCLFaaJhDhmwvnMzk

# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=organization0105@gmail.com
spring.mail.password=xhbq ekdn qrgn lgfd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.address=0.0.0.0
server.port=${PORT:8080}